RATE_LIMIT_THRESHOLD = 50
RATE_LIMIT_WINDOW = 10

IP_REQUESTS_PER_SECOND = 10
IP_REQUESTS_PER_MINUTE = 100

VIOLATIONS_FOR_TEMP_BAN = 3
VIOLATIONS_FOR_BLACKLIST = 10
BASE_BAN_SECONDS = 60
BAN_MULTIPLIER = 2
MAX_BAN_SECONDS = 3600

FULL_CACHE_MAX_ENTRIES = 10000
FULL_CACHE_MAX_MEMORY_BYTES = 100 * 1024 * 1024
FULL_CACHE_TTL_SECONDS = 300

INTERMEDIATE_CACHE_MAX_PER_TABLE = 1000
INTERMEDIATE_CACHE_TTL_SECONDS = 300

QUERY_HISTORY_MAX_ENTRIES = 50000
QUERY_HISTORY_TTL_SECONDS = 60
QUERY_HISTORY_CLEANUP_INTERVAL = 30

MAX_QUERY_LENGTH = 10000
MAX_BODY_SIZE = 50000
BLOCKED_SQL_KEYWORDS = {"DROP", "DELETE", "TRUNCATE", "ALTER", "EXEC", "GRANT", "REVOKE"}
